# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.error_response import ErrorResponse
from .models.settings import Settings

# import apis into sdk package
from .apis.veritas_information_classifier_vic_api import VeritasInformationClassifierVICApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
